1.  SELECT producto.nombre FROM producto;
2.  SELECT producto.nombre,producto.precio FROM producto;
3.  SHOW COLUMNS from producto;
4.  SELECT producto.nombre,producto.precio,(producto.precio * 1.05) FROM producto;
5.  SELECT producto.nombre AS producto,producto.precio AS euros,(producto.precio * 1.05) AS dolars FROM producto;
6.  SELECT UPPER(producto.nombre) AS producto,producto.precio AS euros FROM producto;
7.  SELECT LOWER(producto.nombre) AS producto,producto.precio AS euros FROM producto;
8.  SELECT fabricante.nombre,UPPER(SUBSTRING(fabricante.nombre,1,2)) FROM fabricante;
9.  SELECT producto.nombre,ROUND(producto.precio) FROM producto;
10. SELECT producto.nombre,TRUNCATE(producto.precio,0) FROM producto;
11. SELECT DISTINCT codigo_fabricante FROM producto JOIN tienda.fabricante ON producto.codigo_fabricante = fabricante.codigo;
12. SELECT DISTINCT codigo_fabricante FROM producto JOIN tienda.fabricante ON producto.codigo_fabricante = fabricante.codigo;
13. SELECT nombre FROM fabricante ORDER BY nombre ASC;
14. SELECT nombre FROM fabricante ORDER BY nombre DESC;
15. SELECT nombre FROM producto ORDER BY nombre ASC, precio DESC;
16. SELECT * FROM fabricante LIMIT 5;
17. SELECT * FROM fabricante LIMIT 3,2;
18. SELECT * FROM producto ORDER BY precio ASC LIMIT 1;
19. SELECT * FROM producto ORDER BY precio DESC LIMIT 1;
20. SELECT * FROM producto WHERE codigo_fabricante = 2;
21. SELECT producto.nombre,producto.precio,fabricante.nombre FROM producto JOIN tienda.fabricante ON producto.codigo_fabricante = fabricante.codigo;
22. SELECT producto.nombre,producto.precio,fabricante.nombre FROM producto JOIN tienda.fabricante ON producto.codigo_fabricante = fabricante.codigo ORDER BY fabricante.nombre;
23. SELECT producto.nombre,producto.precio,producto.codigo_fabricante,fabricante.nombre FROM producto JOIN tienda.fabricante ON producto.codigo_fabricante = fabricante.codigo;
24. SELECT producto.nombre,producto.precio,fabricante.nombre FROM producto JOIN tienda.fabricante ON producto.codigo_fabricante = fabricante.codigo ORDER BY producto.precio LIMIT 1;
25. SELECT producto.nombre,producto.precio,fabricante.nombre FROM producto JOIN tienda.fabricante ON producto.codigo_fabricante = fabricante.codigo ORDER BY producto.precio DESC LIMIT 1;
26. SELECT producto.nombre, fabricante.nombre FROM producto JOIN tienda.fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre = "Lenovo";
27. SELECT producto.nombre, producto.precio, fabricante.nombre FROM producto JOIN tienda.fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre = "Crucial" AND producto.precio > 200;
28. SELECT producto.nombre, fabricante.nombre FROM producto JOIN tienda.fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre = "Crucial" OR fabricante.nombre = "Asus" OR fabricante.nombre = "Hewlett-Packard";
29. SELECT producto.nombre, fabricante.nombre FROM producto JOIN tienda.fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre IN ("Crucial","Asus","Hewlett-Packard");
30. SELECT producto.nombre, fabricante.nombre FROM producto JOIN tienda.fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE SUBSTRING(fabricante.nombre,-1) = "e";
31. SELECT producto.nombre,producto.precio FROM producto JOIN tienda.fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre LIKE '%w%';
32. SELECT producto.nombre,producto.precio,fabricante.nombre FROM producto JOIN tienda.fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE producto.precio >= 180 ORDER BY producto.precio DESC,producto.nombre ASC;	
33. SELECT DISTINCT fabricante.codigo,fabricante.nombre FROM fabricante JOIN tienda.producto ON producto.codigo_fabricante = fabricante.codigo;
34. SELECT fabricante.nombre FROM fabricante;
35. SELECT DISTINCT fabricante.nombre FROM fabricante;
36. SELECT producto.nombre, fabricante.nombre FROM producto LEFT JOIN tienda.fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre = "Lenovo";
37. SELECT * FROM producto WHERE precio = (SELECT MAX(precio) FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Lenovo'));
38. SELECT * FROM producto LEFT JOIN tienda.fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre = "Lenovo" ORDER BY producto.precio DESC LIMIT 1;
39. SELECT * FROM producto LEFT JOIN tienda.fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre = "Hewlett-Packard" ORDER BY producto.precio ASC LIMIT 1;
40. SELECT * FROM producto LEFT JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE producto.precio >= (SELECT MAX(precio) FROM producto LEFT JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre = "Lenovo");
41. SELECT * FROM producto LEFT JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE producto.precio >= (SELECT AVG(precio) FROM producto LEFT JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre = "Asus");

